
CREATE TABLE COMERCIO ( 
  RTN INTEGER NOT NULL, 
  Cant_Maquinas INTEGER, 
  Nom_Com VARCHAR(30),
  Tipo_Com VARCHAR(9),
  Ubicacion VARCHAR(30),
  Zona VARCHAR(30),
  PRIMARY KEY (RTN)
);

CREATE TABLE TECNICO(
  ID_Tec INTEGER NOT NULL,
  Nom_Tec VARCHAR(30),
  Sueldo_Tec FLOAT NOT NULL,
  Reparaciones INTEGER default 0 NOT NULL,
  PRIMARY KEY(ID_Tec)
);

-- SELECT * FROM TECNICO;

CREATE TABLE ENSAMBLAJE(
		Cod_Ensam VARCHAR(8) NOT NULL,
		Estado_En VARCHAR(20) NOT NULL,
		ID_Tec_Ha INTEGER NOT NULL,
		ID_Tec_Re INTEGER NOT NULL,
		FOREIGN KEY (Id_Tec_Ha) REFERENCES TECNICO (ID_Tec),
    FOREIGN KEY (Id_Tec_Re) REFERENCES TECNICO (ID_Tec),
    PRIMARY KEY(Cod_Ensam)
);  

CREATE TABLE PROVEEDORES (
  ID_Proveedor INTEGER NOT NULL,
  Nom_Prov VARCHAR(30),
  Ubicacion VARCHAR (30),
  PRIMARY KEY (ID_Proveedor)
);

CREATE TABLE RECAUDACION(
  Cod_Rec VARCHAR(8) NOT NULL,
  Estado_Reneg VARCHAR(1) NOT NULL,
  Bol_Minorista VARCHAR(1) NOT NULL,
  Avg_Rec FLOAT,
  Bol_Mayorista VARCHAR(1) NOT NULL,
  Mont_Men FLOAT,
  Total_Rec FLOAT,
  PRIMARY KEY(Cod_Rec)
);

CREATE TABLE MAQUINA(
  Num_Fallos INTEGER,
  Tipo_Maq VARCHAR(30) NOT NULL,
  Num_Serie VARCHAR(8) NOT NULL,
  Estado_Maq VARCHAR(30),
  RTN_Com INTEGER NOT NULL, 
  PRIMARY KEY (Num_Serie),
  FOREIGN KEY (RTN_Com) REFERENCES COMERCIO(RTN)
);

CREATE TABLE REPARACION(
  Cod_Rep VARCHAR(8) NOT NULL,
  Zona_Rep VARCHAR(30),
  ID_Tec_Rep INTEGER NOT NULL,
  Num_Serie_Maq VARCHAR(8) NOT NULL,
  PRIMARY KEY(Cod_Rep),
  FOREIGN KEY (ID_Tec_Rep) REFERENCES TECNICO (ID_Tec),
  FOREIGN KEY (Num_Serie_Maq) REFERENCES MAQUINA (Num_Serie)
);  

CREATE TABLE HACER_MAQUINA(
Cod_Ensam VARCHAR(8) NOT NULL, 
Num_Serie_HM VARCHAR(8) NOT NULL,
FOREIGN KEY (Cod_Ensam) REFERENCES ENSAMBLAJE(Cod_Ensam),
FOREIGN KEY (Num_Serie_HM) REFERENCES MAQUINA (Num_Serie)
);

CREATE TABLE RECAUDACION_COMERCIO(
  RTN_RC INTEGER NOT NULL, 
  Cod_Rec_RC VARCHAR(8) NOT NULL,
  FOREIGN KEY (RTN_RC) REFERENCES COMERCIO(RTN),
  FOREIGN KEY (Cod_Rec_RC) REFERENCES RECAUDACION(Cod_Rec)
);

CREATE TABLE PIEZA(
  Num_Serie_MPieza VARCHAR(8) NOT NULL,
  ID_Proveedor_Pieza INTEGER NOT NULL,
  No_Serie VARCHAR(8) NOT NULL,
  Marca_Pieza VARCHAR(30),
  Cod_Rep_Pieza VARCHAR(8) NOT NULL,
  Tipo_Pieza VARCHAR(7) NOT NULL,
  PRIMARY KEY(No_Serie),
  FOREIGN KEY (Num_Serie_MPieza) REFERENCES MAQUINA (Num_Serie),
  FOREIGN KEY (ID_Proveedor_Pieza) REFERENCES PROVEEDORES (ID_Proveedor),
  FOREIGN KEY (Cod_Rep_Pieza) REFERENCES REPARACION (Cod_Rep)
);

CREATE TABLE BITACORA(
  IdOp int  GENERATED ALWAYS AS IDENTITY MINVALUE 1, 
  Accion Varchar(60),
  Usuario Varchar(20),
  Fecha DATE,
  Tabla Varchar(30),
  PRIMARY KEY (IdOp)
);
