--Agrega la Inserci�n a la Bit�cora
CREATE OR REPLACE TRIGGER INSERT_REPARACION
  AFTER INSERT ON REPARACION
      FOR EACH ROW
        DECLARE
        V_USERNAME Varchar(20);
        V_FECHA DATE;
        BEGIN
          SELECT User INTO V_USERNAME FROM DUAL;
          SELECT CAST (SYSTIMESTAMP AS DATE) INTO V_FECHA FROM DUAL;
          INSERT INTO BITACORA (Accion,Usuario,Fecha ,Tabla) VALUES ('Insercion'||:NEW.COD_REP, V_USERNAME,V_Fecha,'REPARACION');
        END;
/

--Agrega la Eliminaci�n a la Bit�cora
CREATE OR REPLACE TRIGGER DELETE_REPARACION
  BEFORE DELETE ON REPARACION
      FOR EACH ROW
        DECLARE
        V_USERNAME Varchar(20);
        V_FECHA DATE;
        BEGIN
          SELECT User INTO V_USERNAME FROM DUAL;
          SELECT CAST (SYSTIMESTAMP AS DATE) INTO V_FECHA FROM DUAL;
          INSERT INTO BITACORA (Accion,Usuario,Fecha ,Tabla) VALUES('Eliminacion '||:OLD.COD_REP,V_USERNAME,V_Fecha,'REPARACION');
        END;
/

--Agrega la Actualizaci�n a la Bit�cora
CREATE OR REPLACE TRIGGER UPDATE_REPARACION
  AFTER UPDATE ON REPARACION
      FOR EACH ROW
        DECLARE
        V_USERNAME Varchar(20);
        V_FECHA DATE;
        BEGIN
          SELECT User INTO V_USERNAME FROM DUAL;
          SELECT CAST (SYSTIMESTAMP AS DATE) INTO V_FECHA FROM DUAL;
          INSERT INTO BITACORA (Accion,Usuario,Fecha ,Tabla) VALUES('Actualizacion '||:NEW.COD_REP,V_USERNAME,V_Fecha,'REPARACION');
        END;
/

-- PROCEDIMIENTOS ALMACENADOS
CREATE OR REPLACE PROCEDURE Create_Reparacion(
  ZONA_REP IN VARCHAR,
  NUM_SERIE_MAQ IN VARCHAR)
  AS
    aux INTEGER;
    CODI_REP INTEGER;
    COD_TEC INTEGER;
    
    BEGIN
    SELECT T.ID_TEC INTO COD_TEC FROM TECNICO T WHERE T.REPARACIONES IN(SELECT MIN(REPARACIONES) FROM TECNICO GROUP BY REPARACIONES) AND rownum = 1
    WHILE (true)
        LOOP
          SELECT round(dbms_random.value(1,1000000))  INTO  CODI_REP from dual;
          SELECT COUNT(*) INTO aux FROM REPARACION WHERE Cod_Rep=CODI_REP;
          EXIT WHEN (aux<1);
        END LOOP;
        INSERT INTO REPARACION VALUES (to_char(CODI_REP), ZONA_REP, COD_TEC, NUM_SERIE_MAQ);
    END;
/